### ISSUE TITLE
makefile target: 'linwater' does not work on clean repo!

### ISSUE THREAD

**Issue by ranma1988** [buyuk-dev/water-opengl#3]
$ make linwater 
> g++ -std=c++11 -g -o bin/linwater src/main.cpp -I./include/ -I/usr/include/SDL2/ -I/usr/include/GL/ -lSDL2 -lGLEW -lGL -lGLU -lglut
> /usr/bin/ld: cannot open output file bin/linwater: No such file or directory
> collect2: error: ld returned 1 exit status
> make: *** [makefile:17: linwater] Error 1

**Comment by buyuk-dev** [comment]
fixed by adding bin/ directory to the repository
